on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

name: Run Tests

jobs:
  deploy:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install required packages and run tests
        run: |
          pip install boto3
          cd jmeter-icap-poc/cloudformation
          python3 create_stack.py --total_users 20 --ramp_up=20 --duration=900 --influx_host=${INFLUX_HOST}
        env:
          BUCKET: ${{ secrets.BUCKET }}
          FILE_NAME: ${{ secrets.FILE_NAME }}
          INFLUX_HOST: ${{ secrets.INFLUX_HOST }}

