on:
  workflow_dispatch:
  push:
    branches:
    - master
    - test_github_actions

name: Run Tests

jobs:
  deploy:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install required packages and run tests
        run: |
          pip install boto3
          cd jmeter-icap-poc/cloudformation
          python3 create_stack.py --total_users 1000
        env:
          BUCKET: ${{ secrets.BUCKET }}
          FILE_NAME: ${{ secrets.FILE_NAME }}

